server:
  port: 8080

spring:
  application:
    name: routeit
  datasource:
    url: jdbc:mariadb://localhost:3306/routeit
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.routeit: DEBUG
  file:
    name: logs/routeit.log

