server:
  port: 8080

spring:
  application:
    name: routeit
  datasource:
    url: jdbc:mariadb://3.36.145.87:3306/routeit
    username: routeit
    password: routeit9596
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


